export const ADDQUESTOSTATE = "ADDQUESTOSTATE";
export const REMOVEQUESTIONS = "REMOVEQUESTIONS";
export const AUTHLOADING = "AUTHLOADING";
export const AUTHSUCCESS = "AUTHSUCCESS";
export const AUTHLOGOUT = "AUTHLOGOUT";
export const PROFILELOADING = "PROFILELOADING";
export const PROFILELOADINGSUCCESS = "PROFILELOADINGSUCCESS";
// export const ADDQUESTOSTATE = "ADDQUESTOSTATE";
